docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Introduction: intro.md
    - Reader:
        - "Laminas\\Feed\\Reader": reader.md
        - 'HTTP Clients': http-clients.md
        - 'Importing Feeds': importing.md
        - 'Feed Discovery': find-feeds.md
        - 'Consuming RSS Feeds': consuming-rss.md
        - 'Consuming Atom Feeds': consuming-atom.md
        - 'Consuming Atom Entries': consuming-atom-entry.md
        - Security: security.md
    - Writer: writer.md
    - Pubsubhubbub: pubsubhubbub.md
site_name: laminas-feed
site_description: Laminas\Feed
repo_url: 'https://github.com/laminas/laminas-feed'
